"""add_tenant_id_to_domain_models

Revision ID: 5eb68af93064
Revises: b85ae926578e
Create Date: 2026-05-26 01:07:35.085996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb68af93064'
down_revision: Union[str, Sequence[str], None] = 'b85ae926578e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_addresses_tenant_id'), 'addresses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'addresses', 'tenants', ['tenant_id'], ['id'])
    op.add_column('cart_items', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_cart_items_tenant_id'), 'cart_items', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'tenants', ['tenant_id'], ['id'])
    op.add_column('categories', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_category_tenant_name', 'categories', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'categories', 'tenants', ['tenant_id'], ['id'])
    op.add_column('orders', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.add_column('processed_webhook_events', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'processed_webhook_events', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint('processed_webhook_events_pkey', 'processed_webhook_events', type_='primary')
    op.create_primary_key('pk_processed_webhook_events', 'processed_webhook_events', ['tenant_id', 'event_id'])
    op.add_column('products', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_product_tenant_name', 'products', ['tenant_id', 'name'])
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('uq_user_tenant_email', 'users', ['tenant_id', sa.literal_column('lower(email)')], unique=True)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('uq_user_tenant_email', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_product_tenant_name', 'products', type_='unique')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'processed_webhook_events', type_='foreignkey')
    op.drop_constraint('pk_processed_webhook_events', 'processed_webhook_events', type_='primary')
    op.create_primary_key('processed_webhook_events_pkey', 'processed_webhook_events', ['event_id'])
    op.drop_column('processed_webhook_events', 'tenant_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_column('orders', 'tenant_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_category_tenant_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_column('categories', 'tenant_id')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_tenant_id'), table_name='cart_items')
    op.drop_column('cart_items', 'tenant_id')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_index(op.f('ix_addresses_tenant_id'), table_name='addresses')
    op.drop_column('addresses', 'tenant_id')
    # ### end Alembic commands ###
