"""add password change fields

Revision ID: 7e61388eaffb
Revises: b6dd5452017f
Create Date: 2025-11-28 14:14:59.074403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e61388eaffb'
down_revision: Union[str, Sequence[str], None] = 'b6dd5452017f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_change_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_change_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_change_expires_at')
    op.drop_column('users', 'password_change_token')
    op.drop_column('users', 'pending_password_hash')
    # ### end Alembic commands ###
