"""add quantity constraints and unique constraint to cart_items

Revision ID: 84e9c4800342
Revises: 3680a2718db9
Create Date: 2026-03-24 19:25:03.609414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e9c4800342'
down_revision: Union[str, Sequence[str], None] = '3680a2718db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_cart_user_product', 'cart_items', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_user_product', 'cart_items', type_='unique')
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
