"""add missing indexes and database constraints across all models

Revision ID: b85ae926578e
Revises: d18154818eee
Create Date: 2026-05-25 22:03:51.939695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85ae926578e'
down_revision: Union[str, Sequence[str], None] = 'd18154818eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_changes_product_id'), 'inventory_changes', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_unique_constraint("uq_orders_stripe_checkout_session_id", 'orders', ['stripe_checkout_session_id'])
    op.create_unique_constraint("uq_orders_stripe_payment_intent_id", 'orders', ['stripe_payment_intent_id'])
    op.create_unique_constraint("uq_users_password_reset_token", 'users', ['password_reset_token'])
    op.create_unique_constraint("uq_users_password_change_token", 'users', ['password_change_token'])
    op.create_check_constraint("ck_item_quantity_positive", "order_items", "quantity >= 1")
    op.create_check_constraint("ck_orderItem_price_non_negative", "order_items", "price_at_time >= 0")
    op.create_check_constraint("ck_orderItem_subtotal_non_negative", "order_items", "subtotal >= 0")
    op.create_check_constraint("ck_product_rating_range", "products", "rating >= 0 AND rating <= 5")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_product_rating_range", "products", type_="check")
    op.drop_constraint("ck_orderItem_subtotal_non_negative", "order_items", type_="check")
    op.drop_constraint("ck_orderItem_price_non_negative", "order_items", type_="check")
    op.drop_constraint("ck_item_quantity_positive", "order_items", type_="check")
    op.drop_constraint("uq_users_password_change_token", 'users', type_='unique')
    op.drop_constraint("uq_users_password_reset_token", 'users', type_='unique')
    op.drop_constraint("uq_orders_stripe_payment_intent_id", 'orders', type_='unique')
    op.drop_constraint("uq_orders_stripe_checkout_session_id", 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_inventory_changes_product_id'), table_name='inventory_changes')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    # ### end Alembic commands ###
