"""add cascade delete and quantity check constraint to cart_items

Revision ID: bf0c778a76ca
Revises: 84e9c4800342
Create Date: 2026-03-25 21:18:49.792322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0c778a76ca'
down_revision: Union[str, Sequence[str], None] = '84e9c4800342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
