"""remove unique constraint from tenant owner_email

Revision ID: d18154818eee
Revises: 9d5aafb163fa
Create Date: 2026-05-25 02:29:25.959485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18154818eee'
down_revision: Union[str, Sequence[str], None] = '9d5aafb163fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_owner_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_owner_email'), 'tenants', ['owner_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_owner_email'), table_name='tenants')
    op.create_index(op.f('ix_tenants_owner_email'), 'tenants', ['owner_email'], unique=True)
    # ### end Alembic commands ###
