"""add_payment_method_and_address_id_to_orders

Revision ID: e65f88758d24
Revises: f628a7d18bde
Create Date: 2026-04-12 22:39:42.294642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e65f88758d24'
down_revision: Union[str, Sequence[str], None] = 'f628a7d18bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_id', sa.Integer(), nullable=False))
    payment_method_enum = sa.Enum('cod', name='payment_method')
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('orders', sa.Column('payment_method', sa.Enum('cod', name='payment_method', create_type=False), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'shipped', name='order_status'),
               nullable=False)
    op.create_foreign_key("fk_orders_address_id", 'orders', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_orders_address_id", 'orders', type_='foreignkey')
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'completed', 'cancelled', 'shipped', name='order_status'),
               nullable=True)
    op.drop_column('orders', 'payment_method')
    sa.Enum(name='payment_method').drop(op.get_bind(), checkfirst=True)
    op.drop_column('orders', 'address_id')
    # ### end Alembic commands ###
